regs = 8 # doesnt matter if using "silk"
heap = 256 # size of the heap
bits = 16 # bitlength of target arch
modfix = True # just replaces # with M for mod's emulator to work
complex = True
run = "ram" # can be "ram" or "rom"
stack = 256 # size of the stack in the header
arch = "urcl" # arch can be "urcl" or "silk"
num_reg = True # do numbers go in regs or ram? # set false for silk arch
debug = False # print debugging information